# Generated by Django 5.2.1 on 2026-04-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='age_at_test',
        ),
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='calcium_intake',
        ),
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='physical_activity_level',
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='age_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='alcohol_intake',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='diet_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='hip_bmd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='hip_scandate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='hip_tscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='hipneck_bmd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='hipneck_scandate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='hipneck_tscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='identifier_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='menopause_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='physical_activity_leval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='smoking_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='spine_bmd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='spine_scandate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='spine_tscore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
